### ISSUE TITLE
crashes the target on some urls

### ISSUE THREAD

**Issue by Janpot** [yukinying/chrome-headless-browser-docker#1]
been running the container as `docker run --privileged -p 9222:9222 yukinying/chrome-headless-browser:58.0.3018.3`
Then visit `localhost:9222` and select the target. Then visit the url http://li-bracelet.com/ in the debugger window. The page starts loading but then the target crashes (tried with the remote protocol and received `Inspector.targetCrashed` events as well)

![image](https://cloud.githubusercontent.com/assets/2109932/23339153/2d247a74-fc1c-11e6-9b91-13c1cabbb872.png)

Doesn't happen in Chrome run outside a container

**Comment by yukinying** [comment]
I saw that you have reported the issue in https://bugs.chromium.org/p/chromium/issues/detail?id=696361 and will keep watching it. 

I currently have no clue why this happens.

**Comment by yukinying** [comment]
I have spoken too early. Could you try running your docker container with `--shm-size=256m` or `--shm-size=1024m`?
