### ISSUE TITLE
Headless mode, cannot resize window

### ISSUE THREAD

**Issue by abacaj** [yukinying/chrome-headless-browser-docker#11]
Trying to resize window handle to generate larger screenshots:

Getting exception from selenium client:
`browser.Manage().Window.Size <- new Drawing.Size(1400, 900)`
`Additional information: unknown error: cannot get automation extension`

**Comment by yukinying** [comment]
Would passing "--window-size" to the chromeOptions args field works for you? 
See: http://peter.sh/experiments/chromium-command-line-switches/

**Comment by abacaj** [comment]
Seems to manifest when there is a different version of chrome vs chromedriver. Is that possible?

**Comment by abacaj** [comment]
I tried locally on my machine, using latest stable chrome and chromedriver 2.9 worked correctly

**Comment by yukinying** [comment]
Do you mind sharing a minimal set of code that could reproduce the issue?

**Comment by abacaj** [comment]
The code I wrote is in javascript (node)

```
function getRemoteBrowser() {
    var activePlatform =  {
        "browserName": "chrome",
        "deviceName": "chrome",
        "platformName": "LINUX"
    };
    var browser = new webdriver.Builder()
        .withCapabilities(activePlatform)
        .usingServer('http://192.168.33.10:4444/wd/hub')
        .build();

    var driverWindow = driver.manage().window();

    driverWindow.maximize() // here

    return browser;
}
```

**Comment by yukinying** [comment]
According to https://bugs.chromium.org/p/chromedriver/issues/detail?id=1625#c39, headless mode does not support using extension to set the windows size, which seems to be what driver.manage().window().maximize() performed.  

I believe that you can just use "--window-size" to set the dimension instead.

**Comment by abacaj** [comment]
Cool, thank you for finding that. I will use the arguments then.

**Comment by alenadasan** [comment]
"--window-size" not working either.

**Comment by yukinying** [comment]
Interesting. I am not able to reproduce it:

```
docker run --init -it --rm --name chrome --shm-size=1024m --cap-add=SYS_ADMIN \
  --entrypoint=/usr/bin/google-chrome-unstable \
  yukinying/chrome-headless-browser \
  --headless --disable-gpu --window-size=200,300 \
  --dump-dom http://howbigismybrowser.com/
```

And the result contains the correct dimension:

```
<div id="counter">
  <span class="num">200</span>
  <span id="divider"></span>
  <span class="num">300</span>
</div>
```
