### ISSUE TITLE
some errors maybe related to wrong build?

### ISSUE THREAD

**Issue by hbakhtiyor** [yukinying/chrome-headless-browser-docker#15]
i posted [here](https://groups.google.com/a/chromium.org/forum/#!topic/headless-dev/4SBVe_Yfk9I) and thought maybe related to wrong build, 

e.g. can't find some file

```
ERROR:gl_implementation.cc(246)] Failed to load /opt/google/chrome-unstable/libosmesa.so: /opt/google/chrome-unstable/libosmesa.so: cannot open shared object file: No such file or directory
```

**Comment by yukinying** [comment]
Are you running the chrome-headless-browser or chrome-headless-browser-selenium? It would help if you could provide the step to reproduce that.

**Comment by hbakhtiyor** [comment]
only chrome-headless-browser, and the steps on the post

**Comment by yukinying** [comment]
It looks like something on argument handling breaks between v59 to v60. Yet you may realize the error does not actually crash the browser.

The following links (https://news.ycombinator.com/item?id=14240460 and https://bugs.chromium.org/p/chromium/issues/detail?id=695212) may have more insights.

**Comment by hbakhtiyor** [comment]
yeah, thanks
