### ISSUE TITLE
what do you think about alpine based image?

### ISSUE THREAD

**Issue by hbakhtiyor** [yukinying/chrome-headless-browser-docker#18]
is it worth to try it? can it decrease the sizes?

e.g. some docker selenium chrome alpine based
https://hub.docker.com/r/yellowblackandwhite/alpine-chrome/
https://github.com/Leafney/alpine-selenium-chrome

**Comment by yukinying** [comment]
I tried that for some time and did not get any progress. I think I have succeeded for once but the image size was about same as the library installed were leaving a heavy footprint. If you have a recipe that works with it, I could build one with a special tag.

**Comment by yukinying** [comment]
Also, chromium in apk

**Comment by hbakhtiyor** [comment]
would be nice to build it
