### ISSUE TITLE
Install a chinese font

### ISSUE THREAD

**Issue by Janpot** [yukinying/chrome-headless-browser-docker#2]
Fonts on Chinese websites are rendered as boxes. It can be fixed by adding a font like `apt-get install fonts-wqy-zenhei`

before:
![screen shot 2017-02-27 at 16 45 33](https://cloud.githubusercontent.com/assets/2109932/23367868/30677c2c-fd0c-11e6-860b-d786b30c12a6.png)

after:
![screen shot 2017-02-27 at 16 44 13](https://cloud.githubusercontent.com/assets/2109932/23367873/35d78c24-fd0c-11e6-9455-c8ec4eebda33.png)

**Comment by Janpot** [comment]
this page seems to have font problems as well http://www.zitikoudai.com/chinese-fonts/huawen/Songti-SC-Regular.html

**Comment by yukinying** [comment]
@Janpot, do you have any idea what font would be required for rendering the page?
