### ISSUE TITLE
E: Package 'ttf-unfonts-core' has no installation candidate

### ISSUE THREAD

**Issue by hbakhtiyor** [yukinying/chrome-headless-browser-docker#20]
during building image

**Comment by yukinying** [comment]
Fixed in commit 6c2fd20ec82de01befba843327bf2d7dfe435b28

**Comment by hbakhtiyor** [comment]
don't need `ttf-unfonts-core` anymore?

**Comment by yukinying** [comment]
I added that a couple months ago based on https://wiki.debian.org/Fonts#Commonly_Used_Fonts. But the package page (https://packages.debian.org/jessie/ttf-unfonts-core) is indicating that the package is obsolete.

**Comment by hbakhtiyor** [comment]
i see

**Comment by hbakhtiyor** [comment]
now different error, https://github.com/yukinying/chrome-headless-browser-docker/issues/21
