### ISSUE TITLE
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation

### ISSUE THREAD

**Issue by hbakhtiyor** [yukinying/chrome-headless-browser-docker#21]

**Comment by yukinying** [comment]
No wonder, debian has a new release on Jun 17th. https://www.debian.org/releases/

**Comment by saifrehman15** [comment]
I got the same error when in run the following command on windows 10 git-bash
docker-compose up -d --build
Any Solution?

**Comment by yukinying** [comment]
I can't reproduce this. I think you may be using an old version?

**Comment by saifrehman15** [comment]
I have fixed this issues by putting following line in dockerfile after line 7.
RUN apt-get update && apt-get install -my wget gnupg

**Comment by yukinying** [comment]
Sorry I am not following, perhaps I missed something. When the container image is built with Travis CI, it does not have any issue: https://travis-ci.org/yukinying/chrome-headless-browser-docker/jobs/396753750#L1495. (Please see the next paragraph for the traces). Is your setup different from the one in this repository?

```
Sending build context to Docker daemon  3.072kB
Step 1/9 : FROM debian:stable-slim
stable-slim: Pulling from library/debian
a88163799460: Already exists
Digest: sha256:d1ad951898b7c9ee9b71421909bf990749f9b4a5336ce50af3e4453e1c0a52f7
Status: Downloaded newer image for debian:stable-slim
 ---> e0f4a3fee490
Step 2/9 : MAINTAINER Albert Yu <[secure]@gmail.com>
 ---> Running in 46eedecd81f3
 ---> f6d97878f8d2
Removing intermediate container 46eedecd81f3
Step 3/9 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Running in 5735daca85b1
 ---> e9a91847878a
Removing intermediate container 5735daca85b1
Step 4/9 : RUN apt-get update -qqy   && apt-get -qqy install        dumb-init gnupg wget ca-certificates apt-transport-https        ttf-wqy-zenhei   && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
 ---> Running in f8e4ea393b3f
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libexpat1:amd64.
(Reading database ... 6315 files and directories currently installed.)
Preparing to unpack .../00-libexpat1_2.2.0-2+deb9u1_amd64.deb ...

[omitted for brevity...]

0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
 ---> f2d75e44f9e4
Removing intermediate container f8e4ea393b3f
Step 5/9 : RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -   && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list   && apt-get update -qqy   && apt-get -qqy install google-chrome-unstable   && rm /etc/apt/sources.list.d/google-chrome.list   && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
 ---> Running in b5a55a3e5286
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 7365 files and directories currently installed.)
Preparing to unpack .../perl-base_5.24.1-3+deb9u4_amd64.deb ...

[omitted for brevity...]

Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.36.5-2+deb9u2) ...
 ---> 89a8b79b56d9
Removing intermediate container b5a55a3e5286
Step 6/9 : RUN useradd headless --shell /bin/bash --create-home   && usermod -a -G sudo headless   && echo 'ALL ALL = (ALL) NOPASSWD: ALL' >> /etc/sudoers   && echo 'headless:nopassword' | chpasswd
 ---> Running in 9a7f0438e522
 ---> c93dde0d0d2e
Removing intermediate container 9a7f0438e522
Step 7/9 : RUN mkdir /data && chown -R headless:headless /data
 ---> Running in 991566e584e8
 ---> 26d5f3583676
Removing intermediate container 991566e584e8
Step 8/9 : USER headless
 ---> Running in 6165db7cc3a3
 ---> 2af6c8b12e96
Removing intermediate container 6165db7cc3a3
Step 9/9 : ENTRYPOINT /usr/bin/dumb-init -- /usr/bin/google-chrome-unstable --disable-gpu --headless --disable-dev-shm-usage --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --user-data-dir=/data
 ---> Running in 286a8e505b6c
 ---> 521ddbb3cd01
Removing intermediate container 286a8e505b6c
Successfully built 521ddbb3cd01
Successfully tagged [secure]/chrome-headless-browser:latest
```

**Comment by saifrehman15** [comment]
Remember I am using windows and following is my build. 
Building web
Step 1/16 : FROM php:5.6-apache
 ---> 17ce7f35ef74
Step 2/16 : COPY ./config/php.ini /usr/local/etc/php/
 ---> Using cache
 ---> 41c01be0f96d
Step 3/16 : ENV APACHE_DOCUMENT_ROOT /var/www/html/web
 ---> Using cache
 ---> 55ef1af7bb32
Step 4/16 : RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
 ---> Using cache
 ---> 623055df1219
Step 5/16 : RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
 ---> Using cache
 ---> 214076b6576a
Step 6/16 : RUN apt-get update && apt-get install -my wget gnupg
 ---> Running in af967367c19b
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:5 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [450 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [12.1 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [9530 kB]
Fetched 10.3 MB in 14s (689 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  dirmngr gnupg-agent gnupg-l10n libassuan0 libksba8 libnpth0 libreadline7
  pinentry-curses readline-common
Suggested packages:
  dbus-user-session libpam-systemd pinentry-gnome3 tor parcimonie xloadimage
  scdaemon pinentry-doc readline-doc
The following NEW packages will be installed:
  dirmngr gnupg gnupg-agent gnupg-l10n libassuan0 libksba8 libnpth0
  libreadline7 pinentry-curses readline-common wget
0 upgraded, 11 newly installed, 0 to remove and 7 not upgraded.
Need to get 4394 kB of archives.
After this operation, 12.9 MB of additional disk space will be used.
Get:1 http://security.debian.org/debian-security stretch/updates/main amd64 gnupg-agent amd64 2.1.18-8~deb9u2 [553 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libassuan0 amd64 2.4.3-2 [42.5 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 pinentry-curses amd64 1.0.0-2 [50.5 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libnpth0 amd64 1.3-1 [14.6 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 readline-common all 7.0-3 [70.4 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libreadline7 amd64 7.0-3 [151 kB]
Get:8 http://security.debian.org/debian-security stretch/updates/main amd64 gnupg amd64 2.1.18-8~deb9u2 [1125 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libksba8 amd64 1.3.5-2 [99.7 kB]
Get:9 http://security.debian.org/debian-security stretch/updates/main amd64 wget amd64 1.18-5+deb9u2 [799 kB]
Get:10 http://security.debian.org/debian-security stretch/updates/main amd64 dirmngr amd64 2.1.18-8~deb9u2 [595 kB]
Get:11 http://security.debian.org/debian-security stretch/updates/main amd64 gnupg-l10n all 2.1.18-8~deb9u2 [893 kB]

**Comment by yukinying** [comment]
I see. If I am not mistaken, the issue you reported is on a Dockerfile you created and is not in the scope of this project.

**Comment by saifrehman15** [comment]
My mistake. Yes , the issue is in docker file.
