### ISSUE TITLE
Doesn't seem to trap TERM or INT signals

### ISSUE THREAD

**Issue by Janpot** [yukinying/chrome-headless-browser-docker#23]
Trying to gracefully shut down by executing

```
docker kill --signal TERM chrome
```

But the container doesn't seem to handle these signals.

**Comment by yukinying** [comment]
This is not needed. Docker has provided an "init" via `docker run --init` since version 1.13. I will update the README accordingly.

**Comment by Janpot** [comment]
I know, and that works, but Kubernetes doesn't expose a counterpart to `--init`.

**Comment by yukinying** [comment]
I see. I need some more time to see why this happened. I believe the container consumer (chrome) has the capability to handle the signal but not sure what went wrong.

**Comment by Janpot** [comment]
There's a good explanation here: https://github.com/Yelp/dumb-init
Basically, signals are handled differently for process PID1. If the process doesn't have custom signal handlers and it runs as PID 1, signals are not passed.
Usually only init systems run as PID 1. So most other applications (like Chrome) are not written with the expectation to be run as PID1. Hence not properly handling the signals when run in a container.
At least, that's my understanding of it.

**Comment by yukinying** [comment]
Yes, and I just wanna spend some time to see if Chrome is actually handling that or not. I read some conversations before that Chrome has a signal handler. But I haven't verified it.
