### ISSUE TITLE
some font mismatch and displaying some unicodes as square symbols

### ISSUE THREAD

**Issue by hbakhtiyor** [yukinying/chrome-headless-browser-docker#25]
The screenshots taken via the [docker version](https://www.dropbox.com/s/vhrzed8lsbskr5o/typography.com.png?dl=0) and [original version](https://www.dropbox.com/s/blawbg32olpb25b/screenshot-www.typography.com-2017-07-11-08-33-08.png?dl=0)

the typography.com was tested.

**Comment by yukinying** [comment]
Interesting. If you could let me know what font I should add, please let me know. This would help to shorten the "discovery" process.

Btw, it looks like the original version is also displaying the symbols in a wrong way. They are shown as triangle instead of square.

**Comment by hbakhtiyor** [comment]
> Btw, it looks like the original version is also displaying the symbols in a wrong way. They are shown as triangle instead of square.

Ah, yeah, I now recognized, in ff displays correctly,

don't know which font to add, maybe to look at https://www.google.com/get/noto ?

**Comment by adamgotterer** [comment]
Not sure if this is still an issue or not. But the officially recommended puppeteer Dockerfile installs some fonts that aren't installed in this project. 

```
apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont
```
via: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker

**Comment by yukinying** [comment]
Adding all the fonts may introduce 50 - 100MB increase in the image size. It may not fit into some use cases. I think it may worth building a new image on top of the existing one that would have the fonts (e.g. chrome-headless-browser-xl).

**Comment by adamgotterer** [comment]
Another option would be to add support for an ENV flag that toggles on and off additional  resources.

**Comment by yukinying** [comment]
A new image (chrome-headless-browser-xl) is now supporting the fonts. (c5414c68ae4d476f9a2e8dfea6c1f91092153d68)
