### ISSUE TITLE
why using unstable version of chrome?

### ISSUE THREAD

**Issue by hbakhtiyor** [yukinying/chrome-headless-browser-docker#3]

**Comment by yukinying** [comment]
Chrome headless mode is built into the release cycle since version 57. This project was started at the time that version 57 was available for unstable (beta) release.

**Comment by hbakhtiyor** [comment]
i see, any reasons why did you use debian over ubuntu on dockerfile?

**Comment by yukinying** [comment]
I believe Ubuntu is based from Debian. Frankly it does not matter much as long as it can be kept compact.
