### ISSUE TITLE
error while loading shared libraries: libgconf-2.so.4

### ISSUE THREAD

**Issue by leshik** [yukinying/chrome-headless-browser-docker#34]
Hi,

Selenium version doesn't work for me, here is the error:
```
21:08:58.196 INFO - Mismatched capabilities. Creating a synthetic w3c capability.
21:08:58.198 INFO - Capabilities are: Capabilities {rotatable=false, nativeEvents=false, browserName=chrome, takesScreenshot=false, javascriptEnabled=true, platformName=ANY, version=, platform=ANY, cssSelectorsEnabled=true, }
21:08:58.199 INFO - Capabilities {rotatable=false, nativeEvents=false, browserName=chrome, takesScreenshot=false, javascriptEnabled=true, platformName=ANY, version=, platform=ANY, cssSelectorsEnabled=true, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
21:08:58.200 INFO - Capabilities {rotatable=false, nativeEvents=false, browserName=chrome, takesScreenshot=false, javascriptEnabled=true, platformName=ANY, version=, platform=ANY, cssSelectorsEnabled=true, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
/opt/selenium/chromedriver-2.32: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

**Comment by Endran** [comment]
Seeing it as well:

`Davids-MacBook-Pro:~ hardy$ docker run -it --rm --name chrome --shm-size=1024m --cap-add=SYS_ADMIN -p=127.0.0.1:4444:4444 yukinying/chrome-headless-browser-selenium
14:25:24.358 INFO - Selenium build info: version: '3.6.0', revision: '6fbf3ec767'
14:25:24.359 INFO - Launching a standalone Selenium Server
2018-01-09 14:25:24.392:INFO::main: Logging initialized @365ms to org.seleniumhq.jetty9.util.log.StdErrLog
14:25:24.474 INFO - Driver class not found: com.opera.core.systems.OperaDriver
14:25:24.525 INFO - Driver provider class org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
14:25:24.526 INFO - Driver provider class org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
14:25:24.526 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
14:25:24.573 INFO - Using the passthrough mode handler
2018-01-09 14:25:24.612:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2018-01-09 14:25:24.650:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@731a74c{/,null,STARTING} has uncovered http methods for path: /
2018-01-09 14:25:24.659:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@731a74c{/,null,AVAILABLE}
2018-01-09 14:25:24.688:INFO:osjs.AbstractConnector:main: Started ServerConnector@4f063c0a{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2018-01-09 14:25:24.688:INFO:osjs.Server:main: Started @662ms
14:25:24.688 INFO - Selenium Server is up and running
2018-01-09 14:25:31.831:INFO:osjshC.ROOT:qtp1763847188-10: org.openqa.selenium.remote.server.WebDriverServlet-5e5792a0: Initialising WebDriverServlet
14:25:31.900 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
14:25:31.901 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@25286c5f
14:25:31.908 INFO - /session: Executing POST on /session (handler: BeginSession)
14:25:31.997 INFO - Capabilities are: Capabilities {count=1, browserName=ChromeHeadless, }
14:25:31.999 INFO - Capabilities {count=1, browserName=ChromeHeadless, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
/opt/selenium/chromedriver-2.32: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
14:25:52.036 ERROR - org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127)`

**Comment by yukinying** [comment]
This is fixed by adding the dependency.
