### ISSUE TITLE
Provide a stable chrome version, too

### ISSUE THREAD

**Issue by markuswoessner** [yukinying/chrome-headless-browser-docker#37]
As far as I understand `chrome/Dockerfile` you install chrome unstable (`apt-get -qqy install google-chrome-unstable`). Why not offering a Dockerfile for stable, too?

**Comment by yukinying** [comment]
The idea is to get more artifacts into docker registry. The unstable (I think it is actually from "dev-channel") will get promoted to beta and stable, so we should not need to build the artifacts for the stable version again.

Yet I agree that there is a need to tag the stable version.

**Comment by yukinying** [comment]
After a long period, finally there is a stable version available: https://hub.docker.com/r/yukinying/chrome-headless-browser-stable/tags/. This version is based on Debian chromium package.
