### ISSUE TITLE
Error During Build

### ISSUE THREAD

**Issue by gallofeliz** [yukinying/chrome-headless-browser-docker#42]
Hi,

I have builded on Raspberry pi (ARM arch), and I got this error :

```
E: Unable to locate package google-chrome-unstable
ERROR: Service 'chrome' failed to build: The command '/bin/sh -c wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -   && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list   && apt-get update -qqy   && apt-get -qqy install google-chrome-unstable   && rm /etc/apt/sources.list.d/google-chrome.list   && rm -rf /var/lib/apt/lists/* /var/cache/apt/*' returned a non-zero code: 100
```

Do you know why ?

Regards

**Comment by gallofeliz** [comment]
I think Chrome is not available for this arch. I will try with Chromium - your project fit exactly what I was looking and work perfectly on x64 with a "small" image.

**Comment by yukinying** [comment]
I have played with RPI with Chrome headless shell some time before. Building that is possible but cost a whole day in a fairly average machine. If there is a need for having that, I can see if making a build is possible.

**Comment by gallofeliz** [comment]
Hi,

I have tried during some hours to get a binary, from package managers, from website, read forums, etc, but it is a total failure. A moment I success to get a chromium but I needed XVFB and I was unable to contact it. The I saw version 37 and I understood. Finally I took my x64 computer, wanting compile it, but I didn't understand really how and git clone was 11 Go, that needs some days with my internet.

So, if you have the key for this problem, I take it !

**Comment by yukinying** [comment]
As a side note, have you tried ubuntu armhf build? http://ports.ubuntu.com/pool/universe/c/chromium-browser/ has a couple deb package with arm support.

**Comment by gallofeliz** [comment]
Thanks I will try as soon as possible

**Comment by gallofeliz** [comment]
Hi,

I had the same problem with error about architecture. I change FROM from debian to a special Raspbian and now I have problem with dependencies ... So it works ! Usually, I use alpine and I don't care about these things.

Thanks for your help.

Regards,
