### ISSUE TITLE
cant pass parameters into the chrome drive for image: Chrome Headless Browser with Chrome Driver in Selenium

### ISSUE THREAD

**Issue by geetee24** [yukinying/chrome-headless-browser-docker#43]
Tell me please how to pass command line options into it.

docker run -it --rm --name chrome --shm-size=1024m --cap-add=SYS_ADMIN -p=127.0.0.1:4444:4444 yukinying/chrome-headless-browser-selenium --whitelisted-ips=""

where I want to add: --whitelisted-ips=""

it causes error: 

SYS_ADMIN -p=127.0.0.1:4444:4444 yukinying/chrome-headless-browser-selenium --whitelisted-ips=""
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '--whi
telisted-ips=' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:936)

**Comment by yukinying** [comment]
Not sure if this is still reproducible, please reopen if so. Thanks.
