### ISSUE TITLE
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)

### ISSUE THREAD

**Issue by tomasbruckner** [yukinying/chrome-headless-browser-docker#48]
Hi, I am trying to extend the image (add zip)

```
FROM yukinying/chrome-headless-browser-stable:100.0.4896.127

RUN apt-get update
RUN apt-get install zip unzip
```

But it fails with missing `/var/lib/apt/lists/partial`

I think it is because the user is not a sudoer? Is there any workaround?

**Comment by yukinying** [comment]
Please refer to the Docker manual and see how to use the `USER` command.

As an example, this was how it is used in this repository. https://github.com/yukinying/chrome-headless-browser-docker/blob/d33fbeb5a7166ecb8d9f015bd2529541aa9063da/chrome-stable/Dockerfile#L27
