### ISSUE TITLE
Use TravisCI Cron Jobs

### ISSUE THREAD

**Issue by elgalu** [yukinying/chrome-headless-browser-docker#8]
Instead of relying on a personal machine for the releases you may find useful to use TravisCI new feature: Cron Jobs:

![image](https://cloud.githubusercontent.com/assets/111569/24558400/47ff2a5e-163b-11e7-8cf7-2601ad43c83b.png)

Nice work BTW, I could close [an issue](https://github.com/elgalu/docker-selenium/issues/148) thanks you will be maintaining this repo.

**Comment by yukinying** [comment]
This repository does use Travis CI and cron job - See https://travis-ci.org/yukinying/chrome-headless-browser-docker. 

I have another repository (https://github.com/yukinying/chrome-headless-travis-build) that builds headless-shell with a personal machine. Are you referring to that? Yet that repository can't be built with Travis CI agents as the regular build time takes more than 15 hours.

**Comment by elgalu** [comment]
Nice! yes I got confused by the other one:)
