### ISSUE TITLE
Create a selenium node version

### ISSUE THREAD

**Issue by TomLarrow** [yukinying/chrome-headless-browser-docker#9]
It would be great to have a version that registers with a hub and works in a selenium grid.  

It may be as simple as restoring the lines 37-46 commented out in the Dockerfile.  The standalone version of this image uses several hundred megabytes less of memory per instance than our existing chrome nodes.  As we currently have 50+ nodes in our grid that could be a massive memory savings, which would allow us to either run more nodes, or use that memory for other applications.

**Comment by yukinying** [comment]
I have pushed an update. Please give it a try and see if it works. 
It is also available here: https://hub.docker.com/r/yukinying/chrome-headless-browser-selenium/tags/ (VERSION 60.0.3088.3)

**Comment by yukinying** [comment]
I have also updated the README for the instruction to start the selenium node container:

```
# First, start your hub.
docker run -it --rm --name hub \
  -p=127.0.0.1:4444:4444 \
  selenium/hub

# Then run your node by registering it to the hub
docker run -it --rm --name node-chrome --link hub:hub --cap-add=SYS_ADMIN \
  yukinying/chrome-headless-browser-selenium \
  -role node -hub http://hub:4444/grid/register \
  -nodeConfig /opt/selenium/config.json
```
